import { mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const FAMILIES = [
  'Amiri:wght@400;700',
  'Cairo:wght@400;600;700',
  'Cormorant+Garamond:wght@500;600',
];
const cssUrl = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join('&')}&display=swap`;
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text();
await mkdir('public/fonts', { recursive: true });

let out = '/* generated by scripts/fetch-fonts.mjs — do not edit */\n';
const urlRe = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g;
let rewritten = css;
let count = 0;
for (const m of css.matchAll(urlRe)) {
  const remote = m[1];
  const name = createHash('md5').update(remote).digest('hex').slice(0, 12) + '.woff2';
  const buf = Buffer.from(await (await fetch(remote)).arrayBuffer());
  await writeFile(`public/fonts/${name}`, buf);
  rewritten = rewritten.replace(remote, `/fonts/${name}`);
  count++;
}
out += rewritten.includes('font-display') ? rewritten : rewritten.replaceAll('@font-face {', '@font-face {\n  font-display: swap;');
await writeFile('src/styles/fonts.css', out);
console.log(`fonts: downloaded ${count} files, wrote src/styles/fonts.css`);
